### ISSUE TITLE
Parsing with Square Brackets

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#102]
I realized that with RDA implementation, there may be square brackets in edition and other fields as well (particularly publishers/dates). Could square bracket stripping just be added for all fields?

Or would that make the parser a lot slower?

At the very least, it should be applied to titles (245, 130, 240, 246), edition (300), publisher and dates (250, 256).

**Comment by davekisly** [comment]
It will make the parser slower to apply to all fields and its not a completely trivial operation due to the different field structures. 

Looking quickly at the parser, we are currently stripping off square brackets from these fields: title, title_field (basically the title), field_title_uniform, field_title_alternate, field_dc_creator, field_dc_contributor, dc_relations and (i think) the publisher as well. 

Not sure about dates. Can you point to some examples?

**Comment by Arty-chan** [comment]
One of the fields date is taking from is the 260/264 where publisher is also taken from, but right now, square brackets are clearly not being stripped from dates, so you end up with stuff like this: https://nnels.ca/items/treaty-peoples-treaty-nation-road-map-all-canadians

**Comment by Arty-chan** [comment]
I actually can't imagine when it would need to be applied to creator and contributor (which needs punctuation stripping, but should never have square brackets).

**Comment by davekisly** [comment]
I will review the date parsing this week.

As to square brackets, i don't know the collection well enough to give you a rationale as to why we added that normalization to the creator / contributor fields. I can remove if you prefer.

**Comment by davekisly** [comment]
@Arty-chan - just so we're comparing apples-apples, its helpful if we look at the dates / repo items on DEV and less so on PROD since the latter is somewhat out of date in terms of the parser, etc. 

For example, i grabbed the XML from the example you cite above and created a new entry on DEV: https://dev.nnels.ca/items/treaty-peoples-treaty-nation-road-map-all-canadians

When i parsed the item, it seems to have stripped off the square brackets. I'm not certain if this is a recent update to the parser or not, but my general point is that the code on DEV includes various refinements not yet pushed to Prod.

**Comment by Arty-chan** [comment]
Noted.

In that case, let's make sure it strips square brackets for publisher as well, which it doesn't seem to do right now: https://dev.nnels.ca/items/treaty-peoples-treaty-nation-road-map-all-canadians

If it will improve speed/load, we can remove square bracket stripping from creator/contributor.

**Comment by Arty-chan** [comment]
resolved. Will be pushed up to PROD with #101
