### ISSUE TITLE
S3 File Attachment Runtime

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#123]
When using the "create s3 attachment" operation, right now we pull narrator from 511$a. Please check whether it's also pulling runtime. I've not seen it, but it could simply be because it's rarely actually/properly used.

Pull runtime from 306$a which is in this format: _hhmmss_ into attachment's runtime field.

Examples from MARC records:
306 	##$a002016
306 	##$a014500

**Comment by davekisly** [comment]
As far as my testing went -a couple records on my local w/ 306$a values- the s3 attachment parser is adding in run-time values. There is a catch, tho, namely that the file can't have been previously added to Drupal's file_managed table. 

So i had to hunt for new records (again, on my local) that included URIs which had not already been parsed. When i ran those, the run-times were added.

Can you perhaps point me to one or two records on PROD that don't include files w/ already parsed URIs? Maybe u can use this: 

https://nnels.ca/admin/content/cals/repo-items/marcxml-output?field_keyword_index_value=&field_xml_string_value_1=marc%3Adatafield+tag%3D%22306%22&items_per_page=500

If there's many run-times missing, then perhaps we need some type of batch updater?

**Comment by davekisly** [comment]
After a bit more review, i can see there are a number of running time values missing. As above, i think running times are pulled on new entries (ie., when running the Create S3...). 

I've just pulled together a view on my local to summarize the issue and to possibly use to re-parse those missing values. Will add to DEV tomorrow for your review.

**Comment by Arty-chan** [comment]
if it will only do it for new entries, then yes, we'll need a one-time script. The problem with re-parsing S3 entries is that we may have added narrator/runtime and I don't want to overwrite existing values. Can the one-time script, first check whether the fields are not-empty?

Also, since the runtime field is a max-6-digit field, should the parser do validation? or how is it pulling the information? what happens if there are invalid characters like : ?

I do not have any example of no files but already parsed URIs (because that's not a thing that should happen on PROD). You could use an unpublished record, put in an already used URI, and run the Create attachment operation.

**Comment by davekisly** [comment]
Actually, what we need to test with are URIs (i.e., filepaths) that are NOT in the file_managed table. A bit tricky to explain concisely, but essentially Drupal adds an entry into files_managed for each URI it "knows" about (ones we've fed thru the parser). Also, its tricky because merely deleting the Field Collection entry will not necessarily clear out the files_managed entry (because this is sort of non-typical, CORS s3 stuff). So, in most cases, the entries we want to test with will be newly added records on which we've never run the Create S3 operation.

The parser may do some validation, just can't remember if its on the way into the DB or on its way out when the value is being displayed. I'll check later.

As to a batch-updater, yes, i had intended it to ignore the other fields (i.e., to leave them untouched / as is).

But, another question: let's say a record has 3 attachments. We're pulling run-time from the MARC. Should that value i) apply only to the attachment that matches on the filepath (URI), or would it ii) apply to all 3 attachments? I'm assuming i), but please let me know if its preferable to use w/ each file attachment.

**Comment by Arty-chan** [comment]
A couple of S3 files that should not be in the file managed table:
* http://download.nnels.ca.s3.libraries.coop/AU/WA/ABWA/autoadd/Shelflist.zip
* http://download.nnels.ca.s3.libraries.coop/AU/WA/ABWA/issn/0884-1136_ensign/Ensign-Jan_2010.zip
* http://download.nnels.ca.s3.libraries.coop/AU/WA/ABWA/tech/odt2dtbook.m4b.zip

With batch updater, I'd like to leave existing runtime alone too if it's not-empty.

should only apply to i) as you say. and should match on the repo item "S3 file path" field

**Comment by davekisly** [comment]
@Arty-chan - i need to check w/ Jonathan on accessing the DEV site, but i've got a view on my local that should help identify records with missing run time values.

It will take a bit of time to build the update parser. Probably begin tackling after the long weekend.

**Comment by Arty-chan** [comment]
no problem, thanks for the update

**Comment by davekisly** [comment]
Here's a copy of the view i mentioned: https://dev.nnels.ca/admin/content/cals/repo-items/s3-files-vbo

I'm not completely certain how accurate it is (i had to do some query alters against non-indexed fields, which causes huge overhead), but if you filter on Running Time = null, you should get a record-set comprised mostly of items where there appears to entries that have their file URIs in recorded in files_managed + 306 tags in the marc, but no corresponding run times. So, i believe these are the ones to re-parse the run-times on. 

As i say, i'll start on this early next week.

**Comment by davekisly** [comment]
Had a quick look at the S3 parser this AM (in conjunction w/ ticket #120) and will confirm that (in my tests) its working as expected when parsing new attachments (the original issue raised in this ticket).
