### ISSUE TITLE
Repo Item Fields to Remove

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#125]
Can/should these fields be removed?

* cataloguing details (all): cataloguing agency; and encoding level
* under publishing details: Source; Cover Art URL 
* RDA/DC Types (all): Content Type; Media Type; DC Type
* under Files: URI (as this was replaced by URLs External); Daisy 2 File, File Description, Marc file,
* Indexed fields (admin): Keyword index
* S3 file Attachments (this is a group but has no fields in it)

Also:
* rename Publisher (Source)` without the last character

Can we also hide the following to make it shorter? If it's not just a simple checkbox/setting, then forget it: menu settings, comment settings

Let me know if you have any immediate questions. Feel free to flag any that cannot be removed as well.

**Comment by davekisly** [comment]
Here's a quick view to assist in our discussion: https://dev.nnels.ca/admin/content/cals/repos-items/deprecated-fields

Couple quick comments / replies:

- cataloguing details: these were removed from DEV, so i suspect we've discussed this previously? Think this will be safe to pull from PROD, as well.
- Cover Art URL: we can probably pull this. I have ideas (to discuss w/ Kris) around caching the photos to reduce the overhead of loading the external images. In the meantime, probably ok just to delete this field.
- Forget what MARC file is - perhaps we had anticipated adding a downloadable file on each node? Anyway, the model has shifted (with file attachments / formats) so we should probably revisit.
- Duplicate Managed File is an admin field, used to track nodes that have S3 paths in common with previously parsed entries. So, we need to retain this one for time being.
- Indexed fields: Language is required (its a drupal field). Keyword Index can probably go - originally, it was intended to act as aggregated field of sorts, i.e., to simplify indexing (of genre, subjects, etc.). But the search api index supports this out of the box, so i can delete Keyword Index ... but first need to review the parser to delete references there, as well.
- S3 file attachments - originally, this served as the container for S3 file attachments, but since we add them elsewhere (via the detail node display), then yes, it makes sense to delete the field group.

**Comment by davekisly** [comment]
Also, perhaps the editor kludged your text - can u explain "also rename Publisher (Source) ..."? Should it be Publisher Source (no parenthesis)?

**Comment by Arty-chan** [comment]
yeah, sorry, edited, but what it should point out is that it currently says: Publisher (Source)`

guessing the last character was a typo, but I couldn't figure out how to change it myself

Thanks for the view, will look at it later today

**Comment by Arty-chan** [comment]
it's fine if there are admin fields we need to leave. Will also leave DC Description alone for now.

re: Indexed fields: Language. I noticed most of these say "undefined". We do have a "Language" field as well if that makes a difference?

**Comment by davekisly** [comment]
Yes, most (all?) of the repo entries are language neutral because you aren't translating the actual metadata (e.g., title, abstracts, etc.). We have this field because we've got various localization modules turned on.

The other language field is used to tag the primary language(s) of the files themselves as defined in the MARC record (is it the 041?). E.g., if a Daisy file was in Italian, it should be tagged as such in that long list of checkboxes.

**Comment by Arty-chan** [comment]
so, so we'll leave the admin required and DC Description.

What about under publishing details: Source ? This is obviously distinct from Publisher (Source), so I'm not sure what it refers to.

**Comment by Arty-chan** [comment]
okay, updated the first comment, removing the fields that we're keeping

let me know on the Source field

**Comment by davekisly** [comment]
I've deleted a handful of the fields, including "Source" (under publishing details) which wasn't referenced in the importer code anywhere. Likewise, the Keyword Index.

I hesitated a bit on Content Type and Media Type but checked the importer code and didn't see them referenced anywhere, either, so i ended up deleting those as well.

I hesitated on DC Type, as well, because its invoked in one importer function (_cals_importer_get_controlfield_values_from_marc), but that seems an orphan / ready to be deprecated as well, so no more DC Type (and i also deleted the parent group).

I've left Bibid for the time being because i see it referenced in a function in the External Search module (via cals_external_search_form_alter()). Haven't had a chance to review that more closely, so i'll leave the field for now.

All of the above leaves us w/ the earlier view whittled down considerably to a handful of mostly admin fields:
https://dev.nnels.ca/admin/content/cals/repos-items/deprecated-fields

**Comment by Arty-chan** [comment]
Okay thanks. That just leaves:
* under Files: URI (as this was replaced by URLs External)

**Comment by davekisly** [comment]
I'm looking at that field and see its still invoked when the records are parsed. See _cals_importer_get_uri_from_marc

So, i'll should review this before i delete.

**Comment by davekisly** [comment]
So, looking at the function in question, it seems that we decided to parse 856u tags for any records that do not include nnels.ca, license or loc.gov in the actual URL.

I'm not certain if / how this is actually used in the system, so perhaps its safe to eliminate both the field and the parser?

**Comment by Arty-chan** [comment]
This was the work done for #108 

We should be keeping this function, but the importer should be parsing to the new field which in the repo item is labelled "URLs External". The field that it used to parse to, labelled "URI", shouldn't be referenced anymore, so we should be able to delete it. But wanted you to confirm.

**Comment by davekisly** [comment]
At this point, it looks like we're parsing both fields (i.e., there's a second function _cals_importer_get_urls_from_marc that populates URLs External), so on my next commit, i'll comment out the older function and then we should be good to delete the older field.

**Comment by Arty-chan** [comment]
okay, let me know when that's up and I can do a bit of testing just to make sure everything seems okay before we do this on prod.

**Comment by davekisly** [comment]
ok, i've committed the changes to DEV and also deleted the (old) URI field. Using the following (small) set, i deleted the records and then reparsed: https://dev.nnels.ca/admin/content/cals/records-sets/2016-04-requests-and-griffin

Didn't see any obvious issues, maybe u can test with one of the larger marc record sets?

**Comment by Arty-chan** [comment]
looks good to me.  I think we can go ahead with this on PROD.

**Comment by davekisly** [comment]
I'm going to make the changes (to the field definitions) and pull the importer to PROD over the weekend (possibly tomorrow AM). Will report back when complete.

**Comment by davekisly** [comment]
hi @Arty-chan - i've pulled up the parser updates and deleted the fields mentioned in the first post above (except "DAISY File Available" which i'm leaving from some reason i forget at the moment). Didn't test the parsing, please do so when u have a chance.

**Comment by kpjorgen** [comment]
Hi Dave,

Would any of the changes you made impact the editing of Title-level records in the repo? We are experiencing an issue on prod where we can't seem to save any titles after editing them. The following error appears:

The Subject is using the following invalid tokens: [node:field_keyword_index].
The Source is using the following invalid tokens: [node:field_source].

This is the following record I was working with:

https://nnels.ca/node/20069/edit

Thanks!
Kris

**Comment by davekisly** [comment]
Hi Kris, yes unfortunately that seems the case. Should be an easy fix but I won't be online until later this eve (responding via my phone right now). Hope u can hold off editing those records for the next bit?

**Comment by kpjorgen** [comment]
Hi Dave, not a problem. Let us know when we are all clear and then we'll get going again!
Thanks!

**Comment by davekisly** [comment]
@kpjorgen - this should now be fixed up. To explain, two of the fields we deleted was used to pre-populate various meta-tags. I've updated that configuration and test-saved a couple nodes without seeing any errors. Please test when you have a chance and let me know?

**Comment by kpjorgen** [comment]
Looks like it is working great! Thanks Dave!

**Comment by Arty-chan** [comment]
noticed this was done, so closing
