### ISSUE TITLE
Field 020 > 534$z

### ISSUE THREAD

**Issue by flittle8** [BCLibCoop/nnels#132]
Field 020 needs to be deleted from exporter. The 020 (ISBN and ISBN Audio) data should go in Field 534$z. This subfield is repeatable.

**Comment by davekisly** [comment]
@flittle8 - could you please check a couple records. I updated the code to pull in both ISBN values (each mapped to 534z). Here's an example of a record that has both ISBN types (i added an arbitrary value to ISBN_audio): https://dev.nnels.ca/items/1-dead-attic-after-katrina

Look toward the bottom of the main detail page under the "XML Stub xml" heading.

To my eye, this seems to work ok and i suspect going forward, the publisher details in 534c are likely to be a bit more dirty.

**Comment by flittle8** [comment]
This seems to be working -- thanks!

**Comment by flittle8** [comment]
This record here only takes 1 of the 3 ISBNs into 534$z: https://dev.nnels.ca/items/4th-july

**Comment by davekisly** [comment]
Ugh, you're right. Think i misinterpreted the repeatable to mean one isbn and potentially one isbn_audio. Will refine.

**Comment by davekisly** [comment]
Farrah, have another look at the same record. Just committed some changes to the code and it looks to be fixed. This is what i see:

`<datafield tag="534" ind1=" " ind2=" "><subfield code="z">0316710601</subfield></datafield><datafield tag="534" ind1=" " ind2=" "><subfield code="z">1741337895</subfield></datafield><datafield tag="534" ind1=" " ind2=" "><subfield code="z">0316710601</subfield></datafield><datafield tag="534" ind1=" " ind2=" "><subfield code="z">0983908049809</subfield></datafield>`

Note that i added another fake ISBN to test multiples (which is why we see 4 entries here).

**Comment by flittle8** [comment]
Great, it's working now
