### ISSUE TITLE
Parse / Test single collection item export functionality

### ISSUE THREAD

**Issue by davekisly** [BCLibCoop/nnels#135]
hi @gitschatz, just added (re-added?) the basic single node callback we discussed (verbally) to support the development and testing of marc exports of individual field collection items. You can go to an existing file resource, such as this one: https://dev.nnels.ca/field-collection/field-file-resource/477336 and you should now see a "Build Snippet" link. (We can call it whatever you think appropriate.)

Right now, this returns a var dump of the "stub array" attached to the node. We can chat about next steps here or by phone.

**Comment by gitschatz** [comment]
@davekisly Please find my snippet creation action [here](https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/file-snippet-build-revamp/cals_importer.exporter_file_snippets.inc#L45). Currently  it calls callables in the same file with scheme  _cals_importer_exporter_snippet_callback_{tag} to differentiate them from the other tag callbacks.

**Comment by gitschatz** [comment]
Should I be getting [these file snippet tags](https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/file-snippet-build-revamp/cals_importer.exporter_file_snippets.inc#L58) from another function somewhere like _cals_importer_get_tag_array ? That one seems broken in my branch (returns empty var), due to the MARC tag entities missing from my instance I believe.

**Comment by gitschatz** [comment]
Kamino closed and cloned this issue to BCLibCoop/nnels-drupal-modules-cals_importer
