### ISSUE TITLE
Connector Usage Statistics

### ISSUE THREAD

**Issue by kpjorgen** [BCLibCoop/nnels#77]
Hi Dave,

I would like to begin getting some connector related metrics generating. Primarily, I'm interested in:
 
Connector Usage by Organization
 a. daily/monthly counts of valid users using a connector
 b. daily/monthly counts of non-valid users

I'm not sure exactly what venue these types of statistics would be generated, stored and displayed in (e.g. piwik, NNELS admin side of site, or other), but, ideally, I would like some sort of landing page that I could go to and see the figures, and also export them. Details below:

Month:

ORGANIZATION | JAN | FEB | MAR | and so on...
org name | jan data | feb data | mar data | etc...

Daily:

ORGANIZATION | MON | TUES | WED | and so on...
org name | mon data | tues data | wed data | etc...

I realize this, or parts of this, may be difficult to achieve. And that my table idea might not be the best, or most efficient, way to display the data. I'm really interested in your feedback at this point, and the dev time it might take to get something like this up. We could also just start with monthly figures and see how that goes too.

**Comment by kpjorgen** [comment]
Connector statistics data is looking good. Closing ticket. Will open a new ticket for aggregating the data and displaying it.

Thanks,
Kris

**Comment by kpjorgen** [comment]
Hi Dave -- I just noticed 10.77.110.15 is still recording in the Login stats area. Can you strip these ones out and block them from being recorded?

Thanks,
Kris

**Comment by davekisly** [comment]
hi Kris - they should be filtered out, so that's weird. In any case, yes, will review over the weekend when i tackle the other refinements we spoke about!

**Comment by davekisly** [comment]
hi Kris, on second thought, this (collecting stats from .15 ips) might not be a bad thing. Some (many?) users will come to the site directly via a bookmark (e.g., they open their browser, click on bookmark and/or enter url). In these cases, there are no referring URLs beyond the .15 one. 

Indeed, if you look at the stats page (https://nnels.ca/admin/people/cals/login-stats), which i've just augmented with 2 new fields "Referring URL Type" and "IP address", you will see the overwhelming number of .15 entries are included because the URL type = 1 or 4.

The stats module uses the referring URL immediately before logging in. So, the user may have come from somewhere else (a non .15 referring URL), then clicked around the site for a while before deciding to log in. At that point, the referring URL becomes .15. (In theory, we could track back to the "original" referring URL that brought the user to the site ... but that was a bit beyond the original scope and would require some refactoring.)

**Comment by gitschatz** [comment]
@davekisly Just chiming in to clarify that the log-in entries from 10.77.110.* (local IP) are generated by our connector monitoring script from a different VM and are not actual users. That whole range should be excluded from login stats.

As for referring URLs before log-in, this is tracked well in Piwik's visitor log already, especially when we are looking at the effectiveness of social media, mailouts in promoting the service. The login stats needn't overlap there until the user enters via a calsauthen method and is tallied here.

**Comment by davekisly** [comment]
hi Jonathan / Kris - will expand over the weekend, but to explain quickly, the module does exclude (as far as i recall) direct links via 10.77.110.15 but not where the user is already on the site. Have a look, for example, at ID = 129863 (at people/cals/login-stats). That's an .15 ip, but afaik, its associated w/ an actual user.

That noted, i will review more closely over the weekend and report back.

**Comment by davekisly** [comment]
hi again, Jonathan - ok, its sinking in now. :) My assumption had been that .15 was the IP address of nnels.ca itself. So, to confirm (what now seems self-evident), its safe to strip out all 10.77.110.* entries?

As to tracking urls prior to logging in, nnels_stats needs to do this to help differentiate between the direct referring urls vs. users who come from elsewhere vs. those who might poke around the site prior to logging in. Whatever duplication there is with PIWIK is incidental.

**Comment by gitschatz** [comment]
@davekisly Aye, each connector has a reserved test account associated with it - so yes, please strip that range out.

**Comment by kpjorgen** [comment]
Looks like everything is good. Closing ticket.
